Repository Peralban/Plazza, pull requests merged in 2024-05, with the labels that each got.

#1 :zap: Update issue templates
  .github/ISSUE_TEMPLATE/custom.md
Labels: :building_construction: Architecture

#3 :building_construction: Create base of the project architecture
  .github/workflows/ci.yml
  .gitignore
  Makefile
  Tests/Include/TestsInclude.hpp
  Tests/src/MainTests.cpp
  src/main.cpp
Labels: :building_construction: Architecture, :construction_worker: Continuous Integration

#9 :telephone_receiver: IPC & multi threading communication
  include/messageQueueIPC.hpp
  include/messageQueueThread.hpp
Labels: :sparkles: Enhancement, :building_construction: Architecture

#11 :goal_net: Setup the user command line error handling
  Makefile
  src/Arguments.cpp
  src/Arguments.hpp
  src/Errors/AError.cpp
  src/Errors/AError.hpp
  src/Errors/ArgumentsErrors.hpp
  src/Errors/IError.hpp
  src/main.cpp
  src/shellParser.cpp
  src/shellParser.hpp
Labels: :sparkles: Enhancement

#10 Create kitchen class
  .gitignore
  Makefile
  src/Arguments/Arguments.cpp
  src/Arguments/Arguments.hpp
  src/kitchen/kitchen.cpp
  src/kitchen/kitchen.hpp
  src/main.cpp
  src/messageQueue/messageQueueIPC.hpp
  src/messageQueue/messageQueueThread.hpp
  src/shell/shellParser.cpp
  src/shell/shellParser.hpp
Labels: :sparkles: Enhancement

#16 :ambulance: Fix Kitchen class missing constructor declaration
  src/kitchen/kitchen.cpp
  src/kitchen/kitchen.hpp
Labels: :bug: Bug

#18 :sparkles: Implement the reception
  Makefile
  src/Arguments/Arguments.cpp
  src/Arguments/Arguments.hpp
  src/Reception/Reception.cpp
  src/Reception/Reception.hpp
  src/main.cpp
  src/messageQueue/messageQueueIPC.hpp
  src/shell/runShell.cpp
  src/shell/shellParser.cpp
  src/shell/shellParser.hpp
Labels: :sparkles: Enhancement

#19 :man_cook: Make cook routine
  Makefile
  src/Arguments/Arguments.hpp
  src/kitchen/cook.cpp
  src/kitchen/cook.hpp
  src/kitchen/kitchen.cpp
  src/kitchen/kitchen.hpp
Labels: :sparkles: Enhancement

#23 :link: Setup links from kitchens to reception
  src/Arguments/Arguments.cpp
  src/Arguments/Arguments.hpp
  src/Errors/AError.cpp
  src/Reception/Reception.cpp
  src/Reception/Reception.hpp
  src/kitchen/cook.cpp
  src/kitchen/cook.hpp
  src/kitchen/kitchen.cpp
  src/kitchen/kitchen.hpp
  src/messageQueue/messageQueueIPC.hpp
  src/shell/runShell.cpp
Labels: :sparkles: Enhancement

#25 :children_crossing: Improve the -h option
  src/kitchen/kitchen.cpp
  src/main.cpp
Labels: :sparkles: Enhancement
